package com.littlegreatapps.neodroid;

import java.util.ArrayList;
import fr.mydedibox.emufrontend.CompatibilityList;

public class Compatibility 
{
	public final static int WORKING = 1;
	public final static int PARTIAL = 2;
	public final static int NOT_WORKING = 3;
	public ArrayList<CompatibilityList> list = new ArrayList<CompatibilityList>();
	
	public Compatibility()
	{
		list.add( new CompatibilityList( "3 Count Bout", "3countb.zip", WORKING ) );
		list.add( new CompatibilityList( "2020 Super Baseball (set 1)", "2020bb.zip", WORKING ) );
		list.add( new CompatibilityList( "Alpha Mission II", "alpham2.zip", WORKING ) );
		list.add( new CompatibilityList( "Andro Dunos", "androdun.zip", WORKING ) );
		list.add( new CompatibilityList( "Aggressors of Dark Kombat", "aodk.zip", WORKING ) );
		list.add( new CompatibilityList( "Art of Fighting", "aof.zip", WORKING ) );
		list.add( new CompatibilityList( "Art of Fighting 2", "aof2.zip", WORKING ) );
		list.add( new CompatibilityList( "Art of Fighting 3", "aof3.zip", WORKING ) );
		list.add( new CompatibilityList( "Bakatonosama Mahjong Manyuki", "bakatono.zip", WORKING ) );
		list.add( new CompatibilityList( "Bang Bead", "bangbead.zip", WORKING ) );
		list.add( new CompatibilityList( "Blue's Journey", "bjourney.zip", WORKING ) );
		list.add( new CompatibilityList( "Blazing Star", "blazstar.zip", WORKING ) );
		list.add( new CompatibilityList( "Breakers", "breakers.zip", WORKING ) );
		list.add( new CompatibilityList( "Breakers Revenge", "breakrev.zip", WORKING ) );
		list.add( new CompatibilityList( "Baseball Stars Professional", "bstars.zip", WORKING ) );
		list.add( new CompatibilityList( "Baseball Stars 2", "bstars2.zip", WORKING ) );
		list.add( new CompatibilityList( "Burning Fight (set 1)", "burningf.zip", WORKING ) );
		list.add( new CompatibilityList( "Crossed Swords", "crsword.zip", WORKING ) );
		list.add( new CompatibilityList( "Crouching Tiger Hidden Dragon 2003 Super Plus alternate (The King of Fighters 2001 bootleg)", "ct2k3sa.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Crouching Tiger Hidden Dragon 2003 Super Plus (The King of Fighters 2001 bootleg)", "ct2k3sp.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Crouching Tiger Hidden Dragon 2003 (The King of Fighters 2001 bootleg)", "cthd2003.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Captain Tomaday", "ctomaday.zip", WORKING ) );
		list.add( new CompatibilityList( "Cyber-Lip", "cyberlip.zip", WORKING ) );
		list.add( new CompatibilityList( "Digger Man (prototype)", "diggerma.zip", NOT_WORKING ) );	
		list.add( new CompatibilityList( "Double Dragon", "doubledr.zip", WORKING ) );
		list.add( new CompatibilityList( "Eight Man", "eightman.zip", WORKING ) );
		list.add( new CompatibilityList( "Fatal Fury Special (set 1)", "fatfursp.zip", WORKING ) );
		list.add( new CompatibilityList( "Fatal Fury - King of Fighters", "fatfury1.zip", WORKING ) );
		list.add( new CompatibilityList( "Fatal Fury 2", "fatfury2.zip", WORKING ) );		
		list.add( new CompatibilityList( "Fatal Fury 3 - Road to the Final Victory", "fatfury3.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Football Frenzy", "fbfrenzy.zip", WORKING ) );		
		list.add( new CompatibilityList( "Fight Fever (set 1)", "fightfev.zip", WORKING ) );
		list.add( new CompatibilityList( "Battle Flip Shot", "flipshot.zip", WORKING ) );		
		list.add( new CompatibilityList( "Galaxy Fight - Universal Warriors", "galaxyfg.zip", WORKING ) );
		list.add( new CompatibilityList( "Musashi Ganryuuki", "ganryu.zip", WORKING ) );
		list.add( new CompatibilityList( "Garou - Mark of the Wolves (set 1)", "garou.zip", WORKING ) );
		list.add( new CompatibilityList( "Ghostlop (prototype)", "ghostlop.zip", WORKING ) );
		list.add( new CompatibilityList( "Goal! Goal! Goal!", "goalx3.zip", WORKING ) );
		list.add( new CompatibilityList( "Voltage Fighter - Gowcaizer", "gowcaizr.zip", WORKING ) );	
		list.add( new CompatibilityList( "Ghost Pilots", "gpilots.zip", WORKING ) );
		list.add( new CompatibilityList( "Gururin", "gururin.zip", WORKING ) );
		list.add( new CompatibilityList( "The Irritating Maze", "irrmaze.zip", WORKING ) );
		list.add( new CompatibilityList( "Jyanshin Densetsu - Quest of Jongmaster", "janshin.zip", WORKING ) );
		list.add( new CompatibilityList( "Jockey Grand Prix", "jockeygp.zip", NOT_WORKING ) ); 
		list.add( new CompatibilityList( "Puzzled / Joy Joy Kid", "joyjoy.zip", WORKING ) );
		list.add( new CompatibilityList( "Far East of Eden - Kabuki Klash", "kabukikl.zip", WORKING ) );
		list.add( new CompatibilityList( "Karnov's Revenge / Fighter's History Dynamite", "karnovr.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2003 (bootleg, set 1)", "kf2k3bl.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2003 (bootleg, set 2)", "kf2k3bla.zip", NOT_WORKING ) );	
		list.add( new CompatibilityList( "The King of Fighters 2003 (Japan, JAMMA PCB)", "kf2k3pcb.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2004 Plus / Hero (The King of Fighters 2003 bootleg)", "kf2k3pl.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2004 Ultra Plus (The King of Fighters 2003 bootleg)", "kf2k3upl.zip", NOT_WORKING ) );	
		list.add( new CompatibilityList( "The King of Fighters 10th Anniversary 2005 Unique (The King of Fighters 2002 bootleg)", "kf2k5uni.zip", NOT_WORKING ) );	
		list.add( new CompatibilityList( "The King of Fighters 10th Anniversary Extra Plus (The King of Fighters 2002 bootleg)", "kf10thep.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Kizuna Encounter - Super Tag Battle / Fu'un Super Tag Battle", "kizuna.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters Special Edition 2004 (The King of Fighters 2002 bootleg)", "kof2k4se.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "The King Of Fighters 10th Anniversary (The King of Fighters 2002 bootleg)", "kof10th.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '94", "kof94.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '95 (set 1)", "kof95.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '96 (set 1)", "kof96.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '97 (set 1)", "kof97.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '98 - The Slugfest", "kof98.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters '99 - Millennium Battle (set 1)", "kof99.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2000", "kof2000.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2001 (set 1)", "kof2001.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2002", "kof2002.zip", WORKING ) );
		list.add( new CompatibilityList( "The King of Fighters 2003 (World / US, MVS)", "kof2003.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "King of Gladiator (The King of Fighters '97 bootleg)", "kog.zip", NOT_WORKING ) );		
		list.add( new CompatibilityList( "King of the Monsters (set 1)", "kotm.zip", WORKING ) );
		list.add( new CompatibilityList( "King of the Monsters 2 - The Next Thing", "kotm2.zip", WORKING ) );
		list.add( new CompatibilityList( "Lansquenet 2004 (Shock Troopers - 2nd Squad bootleg)", "lans2004.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Last Blade", "lastblad.zip", WORKING ) );
		list.add( new CompatibilityList( "Last Blade 2", "lastbld2.zip", WORKING ) );
		list.add( new CompatibilityList( "League Bowling", "lbowling.zip", WORKING ) );
		list.add( new CompatibilityList( "Legend of Success Joe", "legendos.zip", WORKING ) );
		list.add( new CompatibilityList( "Last Resort", "lresort.zip", WORKING ) );
		list.add( new CompatibilityList( "Magical Drop II", "magdrop2.zip", WORKING ) );
		list.add( new CompatibilityList( "Magical Drop III", "magdrop3.zip", WORKING ) );
		list.add( new CompatibilityList( "Magician Lord (set 1)", "maglord.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Mahjong Kyoretsuden", "mahretsu.zip", WORKING ) );
		list.add( new CompatibilityList( "Chibi Marukochan Deluxe Quiz", "marukodq.zip", WORKING ) );
		list.add( new CompatibilityList( "Matrimelee", "matrim.zip", WORKING ) );
		list.add( new CompatibilityList( "Money Puzzle Exchanger", "miexchng.zip", WORKING ) );
		list.add( new CompatibilityList( "Minnasanno Okagesamadesu", "minasan.zip", WORKING ) );
		list.add( new CompatibilityList( "Syougi No Tatsujin - Master of Syougi", "mosyougi.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 4 Plus (bootleg)", "ms4plus.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 5 (JAMMA PCB)", "ms5pcb.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 5 Plus (bootleg)", "ms5plus.zip", NOT_WORKING ) );		
		list.add( new CompatibilityList( "Metal Slug - Super Vehicle-001", "mslug.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 2 - Super Vehicle-001/II", "mslug2.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 3", "mslug3.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 4", "mslug4.zip", WORKING ) );
		list.add( new CompatibilityList( "Metal Slug 5", "mslug5.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Metal Slug X - Super Vehicle-001", "mslugx.zip", WORKING ) );
		list.add( new CompatibilityList( "Mutation Nation", "mutnat.zip", WORKING ) );
		list.add( new CompatibilityList( "NAM-1975", "nam1975.zip", WORKING ) );
		list.add( new CompatibilityList( "Ninja Combat (set 1)", "ncombat.zip", WORKING ) );	
		list.add( new CompatibilityList( "Ninja Commando", "ncommand.zip", WORKING ) );	
		list.add( new CompatibilityList( "Neo Bomberman", "neobombe.zip", WORKING ) );
		list.add( new CompatibilityList( "Neo-Geo Cup '98 - The Road to the Victory", "neocup98.zip", WORKING ) );
		list.add( new CompatibilityList( "Neo Drift Out - New Technology", "neodrift.zip", WORKING ) );	
		list.add( new CompatibilityList( "Neo Mr. Do!", "neomrdo.zip", WORKING ) );
		list.add( new CompatibilityList( "Ninja Master's - haoh-ninpo-cho", "ninjamas.zip", WORKING ) );
		list.add( new CompatibilityList( "Nightmare in the Dark", "nitd.zip", WORKING ) );	
		list.add( new CompatibilityList( "Over Top", "overtop.zip", WORKING ) );
		list.add( new CompatibilityList( "Panic Bomber", "panicbom.zip", WORKING ) );
		list.add( new CompatibilityList( "Puzzle Bobble 2 / Bust-A-Move Again", "pbobbl2n.zip", WORKING ) );
		list.add( new CompatibilityList( "Puzzle Bobble / Bust-A-Move (set 1)", "pbobblen.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Pleasure Goal / Futsal - 5 on 5 Mini Soccer", "pgoal.zip", WORKING ) );
		list.add( new CompatibilityList( "Pochi and Nyaa", "pnyaa.zip", PARTIAL ) );
		list.add( new CompatibilityList( "Pop 'n Bounce / Gapporin", "popbounc.zip", PARTIAL ) );
		list.add( new CompatibilityList( "Prehistoric Isle 2", "preisle2.zip", WORKING ) );
		list.add( new CompatibilityList( "Power Spikes II", "pspikes2.zip", PARTIAL ) );
		list.add( new CompatibilityList( "Pulstar", "pulstar.zip", WORKING ) );
		list.add( new CompatibilityList( "Puzzle De Pon! R!", "puzzldpr.zip", WORKING ) );	
		list.add( new CompatibilityList( "Puzzle De Pon!", "puzzledp.zip", WORKING ) );
		list.add( new CompatibilityList( "Quiz Meitantei Neo & Geo - Quiz Daisousa Sen part 2", "quizdai2.zip", WORKING ) );
		list.add( new CompatibilityList( "Quiz Daisousa Sen - The Last Count Down", "quizdais.zip", WORKING ) );
		list.add( new CompatibilityList( "Quiz King of Fighters", "quizkof.zip", WORKING ) );
		list.add( new CompatibilityList( "Ragnagard", "ragnagrd.zip", WORKING ) );	
		list.add( new CompatibilityList( "Real Bout Fatal Fury", "rbff1.zip", WORKING ) );
		list.add( new CompatibilityList( "Real Bout Fatal Fury 2 - The Newcomers", "rbff2.zip", WORKING ) );
		list.add( new CompatibilityList( "Real Bout Fatal Fury Special", "rbffspec.zip", WORKING ) );
		list.add( new CompatibilityList( "Riding Hero (set 1)", "ridhero.zip", WORKING ) );
		list.add( new CompatibilityList( "Robo Army (set 1)", "roboarmy.zip", WORKING ) );
		list.add( new CompatibilityList( "Rage of the Dragons", "rotd.zip", WORKING ) );
		list.add( new CompatibilityList( "Strikers 1945 Plus", "s1945p.zip", PARTIAL ) );
		list.add( new CompatibilityList( "Samurai Shodown V Special", "samsh5sp.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Samurai Shodown", "samsho.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Samurai Shodown II", "samsho2.zip", WORKING ) );		
		list.add( new CompatibilityList( "Samurai Shodown III", "samsho3.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Samurai Shodown IV - Amakusa's Revenge", "samsho4.zip", WORKING ) );
		list.add( new CompatibilityList( "Samurai Shodown V", "samsho5.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Savage Reign", "savagere.zip", WORKING ) );
		list.add( new CompatibilityList( "Super Dodge Ball", "sdodgeb.zip", WORKING ) );
		list.add( new CompatibilityList( "Sengoku", "sengoku.zip", WORKING ) );
		list.add( new CompatibilityList( "Sengoku 2", "sengoku2.zip", WORKING ) );		
		list.add( new CompatibilityList( "Sengoku 3", "sengoku3.zip", WORKING ) );
		list.add( new CompatibilityList( "Shock Troopers - 2nd Squad", "shocktr2.zip", WORKING ) );
		list.add( new CompatibilityList( "Shock Troopers (set 1)", "shocktro.zip", WORKING ) );
		list.add( new CompatibilityList( "Soccer Brawl", "socbrawl.zip", WORKING ) );
		list.add( new CompatibilityList( "Aero Fighters 2 / Sonic Wings 2", "sonicwi2.zip", WORKING ) );
		list.add( new CompatibilityList( "Aero Fighters 3 / Sonic Wings 3", "sonicwi3.zip", WORKING ) );	
		list.add( new CompatibilityList( "Spin Master / Miracle Adventure", "spinmast.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Super Sidekicks", "ssideki.zip", WORKING ) );
		list.add( new CompatibilityList( "Super Sidekicks 2 - The World Championship", "ssideki2.zip", WORKING ) );
		list.add( new CompatibilityList( "Super Sidekicks 3 - The Next Glory", "ssideki3.zip", WORKING ) );
		list.add( new CompatibilityList( "Super Sidekicks 4 (Ultimate 11 - The SNK Football Championship)", "ssideki4.zip", WORKING ) );
		list.add( new CompatibilityList( "Stakes Winner", "stakwin.zip", WORKING ) );
		list.add( new CompatibilityList( "Stakes Winner 2", "stakwin2.zip", WORKING ) );
		list.add( new CompatibilityList( "Street Hoop", "strhoop.zip", WORKING ) );
		list.add( new CompatibilityList( "The Super Spy", "superspy.zip", WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom (MVS)", "svc.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom (MVS) (bootleg)", "svcboot.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom (JAMMA PCB)", "svcpcb.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SVC Chaos - SNK vs CAPCOM (JAMMA PCB, set 2)", "svcpcba.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom Plus (set 1, bootleg)", "svcplus.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom Plus (set 2, bootleg)", "svcplusa.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "SvC Chaos - SNK vs Capcom Super Plus (bootleg)", "svcsplus.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Top Hunter - Roddy & Cathy (set 1)", "tophuntr.zip", WORKING ) );	
		list.add( new CompatibilityList( "Top Player's Golf", "tpgolf.zip", WORKING ) );
		list.add( new CompatibilityList( "Thrash Rally", "trally.zip", WORKING ) );
		list.add( new CompatibilityList( "Neo Turf Masters", "turfmast.zip", WORKING ) );
		list.add( new CompatibilityList( "Twinkle Star Sprites", "twinspri.zip", WORKING ) );
		list.add( new CompatibilityList( "Tecmo World Soccer '96", "tws96.zip", WORKING ) );
		list.add( new CompatibilityList( "Viewpoint", "viewpoin.zip", WORKING ) );
		list.add( new CompatibilityList( "V-Liner (set 1)", "vliner.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "Waku Waku 7", "wakuwak7.zip", WORKING ) );
		list.add( new CompatibilityList( "World Heroes (set 1)", "wh1.zip", WORKING ) );
		list.add( new CompatibilityList( "World Heroes 2", "wh2.zip", WORKING ) );
		list.add( new CompatibilityList( "World Heroes 2 Jet", "wh2j.zip", NOT_WORKING ) );
		list.add( new CompatibilityList( "World Heroes Perfect", "whp.zip", WORKING ) );
		list.add( new CompatibilityList( "Windjammers", "wjammers.zip", WORKING ) );
		list.add( new CompatibilityList( "Zed Blade", "zedblade.zip", WORKING ) );
		list.add( new CompatibilityList( "Zintrick", "zintrckb.zip", WORKING ) );
		list.add( new CompatibilityList( "Zupapa!", "zupapa.zip", WORKING ) );
	}
	
	public ArrayList<CompatibilityList> getList()
	{
		return this.list;
	}
}


